### ISSUE TITLE
Cannot compile Sming example

### ISSUE THREAD

**Issue by sebastian-ruiz** [slaff/esp8266.dev.box#11]
I'm trying to compile the Basic_Blink project for Sming but I get an error. Here is what I did.

I ran $ PROJECT="sming" vagrant provision

Then
$ export ESP_HOME=/opt/Espressif/
$ export SMING_HOME=~/dev/Sming/Sming

I go to the Basic_Blink directory:
$ cd ~/dev/Sming/Samples/Basic_Blink

and $ make

But it fails:
LD out/build/app.out
/opt/Espressif/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: cannot find -lsming
collect2: error: ld returned 1 exit status
make: **\* [out/build/app.out] Error 1

I haven't found anyone online running into the same problem. Thank you for your help.

**Comment by slaff** [comment]
> I ran $ PROJECT="sming" vagrant provision

The command above should set the correct paths and compile the needed code inside of the virtual machine for you.

What you need to do next is to enter the virtual machine
`vagrant ssh`

And INSIDE of the virtual machine to type

```
cd ~/dev/Sming/Samples/Basic_Blink
make
```

You shouldn't set the paths because they should be added automatically from the provisioning script for you. If that is not the case please, tell me what is the output from the following command that should be executed INSIDE the virtual machine:

```
cat /etc/profile.d/esp8266.sh
```

**Comment by sebastian-ruiz** [comment]
Thank you. This issue can be closed.
